### ISSUE TITLE
Vibrate on connection loss not working

### ISSUE THREAD

**Issue by IzzySoft** [aHcVolle/TrekVolle#3]
Any idea why my Pebble Time Steel doesn't vibrate on BT disconnect, despite of the fact I've configured it with the watchface?

In case it matters: FW 4.2, Android 5.1, GadgetBridge 0.19.2 (didn't work with previous versions either).

**Comment by IzzySoft** [comment]
Just a short ping, as there was no response yet: Can you reproduce this, as you're also using GB meanwhile? Any solution on the horizon?

**Comment by aHcVolle** [comment]
wow, i didn't read this till now sorry.
since i switched to GB myself and cloudpebble doesn't seem to be working (right now) i haven't got a dev setup right now so i can't debug this.
The behaviour of the watchface seems to be broken with GB in many ways, i'll see what i can do :)

**Comment by IzzySoft** [comment]
Thanks, thought already you must have missed this (hence the "ping" to create a new notification). I must say for the way you describe it as "broken in many ways", it works excellent – must be amazing when it's no longer broken then :heart_eyes:

No idea what cloudpebble is (I've never used the original software), and I don't have a "dev setup" for Pebble at all. But if I can provide some helpful input, please let me know.

**Comment by aHcVolle** [comment]
cloudpebble is an online compiler / development tool for coding watchfaces/watchapps on the pebble.
I used it before but it seems i have to install a pebble development environment on my local machine.

It's just a matter of free time :)

**Comment by IzzySoft** [comment]
No urgency on my end (I know those "matters of free time"). Good to see you're on it – and it's done when it's done :wink: Guess with the help of the GB team (which they definitely give as I see in the issue you've open there) you'll tackle it quickly, once you've found the time to setup your environment again. Fingers crossed – and I'm very curious for the next version of the watch face, wondering what it will be like when it's no longer "broken in many ways" :grin:

**Comment by aHcVolle** [comment]
Found the bug, will be fixed in the next release

**Comment by IzzySoft** [comment]
Cool! Speaking of which: Would you be so kind and attach the `.pbw` to it so I can grab it? Thanks in advance!

**Comment by aHcVolle** [comment]
Yeah i already did but found another problem why i deleted the file again. I want to fix this before i'll upload it again :)

**Comment by IzzySoft** [comment]
Oh – that reason I cannot and will not oppose, full ack then :grin: Could you please update this issue again when done (serving as a ping to me)?

**Comment by IzzySoft** [comment]
Sorry for the ping, but any ETA on the fix?

**Comment by aHcVolle** [comment]
Sorry, i did upload the source but totally forgot to upload the binary. I've attached the .pbw file to the latest release.
The sports tracking function isn't working so just set the activation level to a high value in the watchapp settings....

**Comment by IzzySoft** [comment]
Thanks! That forced me to finally upgrade the FW on my Pebble a last time (was still running 4.2 on my Pebble Time Steel – now it's on 4.3, and we're unlikely to see something newer).

Just wondering: wasn't it supposed to also show the Android device's battery level now? Or does that only work with "Background JS" enabled? Or did I miss some other "switch"?

**Comment by aHcVolle** [comment]
yes and no, it should work but only does occasionally or i don't remember if i had the background js branch installed when it was working. ... i haven't seen this for a while...

**Comment by IzzySoft** [comment]
Ah, like a direction indicator on a car, just much slower – understood. Shall I open another issue on that? I'd find that more important than having Gadgetbridge showing the watch battery level (much more useful to see both on the Pebble). Or don't you see a chance getting that fixed?

**Comment by aHcVolle** [comment]
i think this has to be fixed on the GB side since i don't know how i could do it other than i did

**Comment by IzzySoft** [comment]
OK, thanks! Then I'll wait until F-Droid publishes the latest version (there's a build pending) and then test with BackgroundJS. Fix must be in that section, I'd assume.
